// Generated by scripts/compile-patterns.mjs from web/patterns/*.not.
// Edit the .not files, then run `pnpm patterns`.
import { ratio } from "./ratio";
import type { Pattern } from "./patterns";

export const PATTERNS: Pattern[] = [
  {
    id: "adi-chatusram-1",
    name: "Adi sarvalaghu, chatusram",
    source: "drafted by Claude from the stroke names, unverified by a mridangist",
    shape: "down one two three down open down open",
    nadai: "chatusram",
    beats: 8,
    strokes: [
      { at: ratio(0, 4), stroke: "L.tham", gain: 1.15 },
      { at: ratio(2, 4), stroke: "R.thi", gain: 1.15 },
      { at: ratio(4, 4), stroke: "R.nam", gain: 1 },
      { at: ratio(6, 4), stroke: "R.thi", gain: 1 },
      { at: ratio(8, 4), stroke: "L.thom", gain: 1 },
      { at: ratio(10, 4), stroke: "R.thi", gain: 1 },
      { at: ratio(12, 4), stroke: "R.nam", gain: 1 },
      { at: ratio(14, 4), stroke: "R.thi", gain: 1 },
      { at: ratio(15, 4), stroke: "R.thi", gain: 1 },
      { at: ratio(16, 4), stroke: "L.tham", gain: 1.05 },
      { at: ratio(18, 4), stroke: "R.thi", gain: 1.05 },
      { at: ratio(20, 4), stroke: "R.nam", gain: 1 },
      { at: ratio(22, 4), stroke: "R.thi", gain: 1 },
      { at: ratio(24, 4), stroke: "L.thom", gain: 1 },
      { at: ratio(26, 4), stroke: "R.thi", gain: 1 },
      { at: ratio(28, 4), stroke: "R.nam", gain: 1 },
      { at: ratio(29, 4), stroke: "R.thi", gain: 1 },
      { at: ratio(30, 4), stroke: "R.nam", gain: 1 },
    ],
  },
];
